#'@title Plotting logistic regression
#'
#'@description
#'The plot function provides single plot that shows separate graphs of the relationship
#'between each predictor and the outcome, controlling for the other predictors from the
#'lreg function
#'
#'@param x an object of type \code{c("lreg", "lm")}
#'@param points points is TRUE if data points are to be shown, default is FALSE
#'@param dot.size size of data points, default is 1
#'@param dot.alpha transparency of data points, default is 0.5
#'@param ci if confidence intervals are to be shown, default is TRUE
#'@param ... additional arguments to be added to adjust graphic
#'
#'@return a plot of class \code{ggplot2}
#'
#'@details
#'The \code{plot.lreg} function is uses ggeffects package to plot the results of the lreg function from the
#'qacReg package. The ggeffects package aims to easily calculate marginal effects and adjusted predictions
#'at representative values of covariates from statistical models, i.e. predictions generated by a model when
#'one holds the controlled dependent variable(s) constant and varies the independent variable(s).
#'To see more details and gain better understanding of the ggeffects package see
#'\link[https://strengejacke.github.io/ggeffects/]{here}
#'
#'
#'@seealso
#'\link[ggeffects]{ggeffect}
#'\link[ggplot2]{ggplot}
#'
#'
#'@export
#'
#'@import ggeffects
#'@import ggplot2
#'@import effects
#'@import patchwork
#'
#'@examples
#'mtcars$am <- factor(mtcars$am)
#'fit <- lreg(am ~ hp + wt + mpg, mtcars)
#'plot(fit)

plot.lreg <- function(x, points = FALSE, dot.size=1, dot.alpha=.5, ci=TRUE, ...){
  vars <- names(x$model)[names(x$model) != x$terms[[2]]]
  myplots <- vector(mode="list", length=length(vars))
  names(myplots) <- vars
  for(i in vars){
    myplots[[i]] <- plot(ggeffect(x, i), add.data=points,
                         dot.size=dot.size, dot.alpha=dot.alpha, ci=ci, ...)+ labs(title="")
  }
  final <- wrap_plots(myplots) + plot_annotation(title="Effects Plots",
                                                 subtitle="Each variable controlling for the others")
  return(final)
}
