#'@title Plotting for linear and logistic regression models
#'
#'@description
#'The \code{plots} function provides a single plot that shows separate graphs of the relationship
#'between each predictor and the outcome, controlling for the other predictors in the model.
#'
#'@param x an object of class \code{"lm"} or \code{"glm"}
#'@param points points is TRUE if data points are to be shown, default is FALSE
#'@param size size of data points, default is 1
#'@param jitter ammount of point jitter (from 0 to 1)
#'@param alpha transparency of data points, default is 0.5
#'@param ci if confidence intervals are to be shown, default is TRUE
#'@param page logical. If \code{TRUE}, each graph will appear separately.
#'@param ... additional arguments to be added to adjust graphic
#'
#'@return a plot of class \code{ggplot2} if \code{page=FALSE}. a list
#'of separate \code{ggplot2} graphs, if \code{page=TRUE} and there is
#'more than one explanatory variable.
#'
#'@details
#'The \code{plots} function is uses ggeffects package to plot the results of the lm or glm functions
#'The ggeffects package aims to easily calculate marginal effects and adjusted predictions
#'at representative values of covariates from statistical models, i.e. predictions generated by a model when
#'one holds the controlled dependent variable(s) constant and varies the independent variable(s).
#'To see more details and gain better understanding of the ggeffects package see
#'\href{https://strengejacke.github.io/ggeffects/}{here}.
#'
#'
#'@seealso
#'\link[ggeffects]{ggeffect}, \link[ggplot2]{ggplot}
#'
#'
#'@export
#'
#'@import ggeffects
#'@import ggplot2
#'@import effects
#'@import patchwork
#'@importFrom stats as.formula coef
#'@importFrom grDevices devAskNewPage
#'
#'@examples
#'fit1 <- lm(mpg ~ hp + wt + accel + origin, data = auto_mpg)
#'plots(fit1)
#'
#'mtcars$am <- factor(mtcars$am)
#'fit2 <- glm(am ~ hp + wt + mpg, family=binomial, mtcars)
#'plots(fit2)


plots <- function(x, points = TRUE, size = 1,
                  alpha=.5, jitter=.03, ci= TRUE, page=FALSE, ...){

  # single predictor
  if (length(names(stats::coef(x))) < 3){
    # scatterplot
    final <- scatter_plot(x, alpha=alpha)
    return(final)
  }

  # create plots
  vars <- names(x$model)[names(x$model) != x$terms[[2]]]
  myplots <- vector(mode="list", length=length(vars))
  names(myplots) <- vars
  for(i in vars){
    myplots[[i]] <- plot(ggeffect(x, i), add.data=points,
                        dot.size=size, jitter=jitter,
                        dot.alpha=alpha, ci=ci, ...)+ labs(title="")
  }

  # produce combined graphs
  if(!page){
    if (length(vars) > 1){
      caption <- "Plots show the relationship of each explanatory variable to\nthe outcome controlling for the other explanatory variables."
    } else {
      caption <- ""
    }

    final <- wrap_plots(myplots) +
      plot_annotation(title="Effects Plots", caption=caption) &
      theme(plot.caption=element_text(size=8))
    return(final)
  }

  # separate graphs
    oask <- grDevices::devAskNewPage(TRUE)
    on.exit(grDevices::devAskNewPage(oask))
    for (i in names(myplots)){
      plot(myplots[[i]])
    }
    invisible(myplots)
}


