#'@title Plotting for linear and logistic regression models
#'
#'@description
#'The \code{plots} function provides a single plot that shows separate graphs of the relationship
#'between each predictor and the outcome, controlling for the other predictors in the model.
#'
#'@param x an object of class \code{"lm"} or \code{"glm"}
#'@param points logical; If TRUE, if raw data are plotted (default=FALSE)
#'@param size size of data points, default is 1
#'@param jitter amount of jitter for points (from 0 to 1; default = .03)
#'@param alpha transparency of data points (from 0 to 1; default is 0.2)
#'@param ci if confidence intervals are to be shown, default is TRUE
#'@param page logical; If \code{TRUE}, each graph will be printed separately.
#'@param ... additional arguments to be passed to
#'\code{\link[ggeffects]{plot.ggeffects}}.
#'
#'@return a list of plots of class \code{ggplot2}.
#'
#'@details
#'The \code{plots} function uses the \code{ggeffects} package to plot the results of the lm or glm functions
#'The ggeffects package aims to easily calculate marginal effects and adjusted predictions
#'at representative values of covariates from statistical models, i.e. predictions generated by a model when
#'one holds the controlled dependent variable(s) constant and varies the independent variable(s).
#'To see more details and gain better understanding of the ggeffects package see
#'\href{https://strengejacke.github.io/ggeffects/}{here}.
#'
#'@section Limitations:
#'The \code{plots} function can not handle models that include
#'\code{as.factor} or \code{factor} in their formulas. Create the modified
#'variables prior to fitting the model
#'(e.g., \code{mtcars$cyl <- factor(mtcars$cyl)}).
#'Additionally, the function can not handle models that include interactions. In this
#'case, consider using the \code{ggeffects} package with grouping and
#'faceting.
#'
#'
#'@seealso
#'\link[ggeffects]{ggeffect}, \link[ggeffects]{plot.ggeffects}
#'
#'
#'@export
#'
#'@import ggeffects
#'@import ggplot2
#'@import effects
#'@import patchwork
#'@importFrom stats as.formula coef
#'@importFrom grDevices devAskNewPage
#'
#'@examples
#'fit1 <- lm(mpg ~ hp + wt + accel + origin, data = auto_mpg)
#'plots(fit1)
#'
#'mtcars$am <- factor(mtcars$am)
#'fit2 <- glm(am ~ hp + wt + mpg, family=binomial, mtcars)
#'plots(fit2)


plots <- function(x, points = FALSE, size = 1,
                  alpha=.2, jitter=.03, ci= TRUE, page=FALSE, ...){

  # single predictor
  if (length(names(stats::coef(x))) < 3){
    # scatterplot
    final <- scatter_plot(x, alpha=alpha)
    return(final)
  }

  # create plots
  # check model
  if(any(grepl("factor\\(", names(x$model)))){
    stop("Unable to handle the factors in the model formula.\nSee ?plots.")
  }
  if(any(grepl("\\:", x$call[[2]]))){
    stop("Unable to handle the interactions.\nSee ?plots.")
  }

  # all variables except dv
  vars <- names(x$model)[names(x$model) != x$terms[[2]]]
  # drop variables with formula (e.g. I(X^2))
  vars <- vars[!grepl("\\(", vars)]
  myplots <- vector(mode="list", length=length(vars))
  names(myplots) <- vars
  for(i in vars){
    myplots[[i]] <- plot(ggeffect(x, i), add.data=points,
                        dot.size=size, jitter=jitter,
                        dot.alpha=alpha, ci=ci, ...)+ labs(title="")
  }

  # produce combined graphs
  if(!page){
    if (length(vars) > 1){
      caption <- "Plots show the relationship of each explanatory variable to\nthe outcome controlling for the other explanatory variables."
    } else {
      caption <- ""
    }

    final <- wrap_plots(myplots) +
      plot_annotation(title="Effects Plots", caption=caption) &
      theme(plot.caption=element_text(size=8))
    return(final)
  }

  # separate graphs
    oask <- grDevices::devAskNewPage(TRUE)
    on.exit(grDevices::devAskNewPage(oask))
    for (i in names(myplots)){
      plot(myplots[[i]])
    }
    invisible(myplots)
}


